# Generated by Django 4.1 on 2023-01-12 08:59

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0004_tag_blog_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='userdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('profileimage', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('phonenumber', models.PositiveIntegerField(max_length=10)),
            ],
        ),
    ]
