# Generated by Django 4.1 on 2023-01-12 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0005_userdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='phonenumber',
            field=models.PositiveIntegerField(),
        ),
    ]
